version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-generator
    container_name: laravel-generator
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx-generator
    restart: unless-stopped
    ports:
      - "5012:80"
    extra_hosts:
      - "generator-faktur.ziadns.my.id:host-gateway"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:
    driver: bridge
