<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Generate Pesan Telkomsel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
        body {
            background-color: #f7f9fc;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 480px;
            margin: 80px auto;
            padding: 30px;
            background: #ffffff;
            border-radius: 12px;
            box-shadow: 0 6px 20px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            margin-bottom: 25px;
            color: #2c3e50;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #34495e;
        }

        input[type="date"] {
            width: 100%;
            padding: 12px;
            border-radius: 6px;
            border: 1px solid #ccc;
            box-sizing: border-box;
            font-size: 16px;
            margin-bottom: 20px;
        }

        button {
            width: 100%;
            background-color: #e74c3c;
            color: white;
            padding: 14px;
            font-size: 16px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }

        button:hover {
            background-color: #c0392b;
        }

        .footer {
            margin-top: 25px;
            text-align: center;
            font-size: 13px;
            color: #aaa;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Generate Pesan Telkomsel</h2>
        <form action="{{ route('pesan.store') }}" method="POST">
            @csrf

            <label for="tanggal">Tanggal Berlaku s/d</label>
            <input type="date" id="tanggal" name="tanggal" required>

            <button type="submit">Generate Gambar Pesan</button>
        </form>

        <div class="footer">
            © {{ now()->year }} Telkomsel Tools – Generated by PAYFAZZ
        </div>
    </div>
</body>
</html>
